sudo: false

language: php

dist: bionic

php:
  - 8.0
  - nightly
 
env: 
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TEST_PHP_ARGS="--show-diff -q" 

install:
  - phpize
  - ./configure
  - make

script: 
  make test

notifications:
  email:
    swen.zanon@geoglis.de
